"$schema" = 'https://starship.rs/config-schema.json'

# print the timestamp on the right hand side
right_format = """$cmd_duration$time"""

[cmd_duration]
format = '[$duration]($style)-'

[directory]
# do not trunc to see which namespace the repo is from
truncate_to_repo = false
# show up to 8 nested folders
truncation_length = 8

[directory.substitutions]
# shorten repo dirs
'~/repos/secustor' = '+/s'
'~/repos/n26' = '+/n'
'~/repos/quellify' = '+/q'

[docker_context]
disabled = true

[git_branch]
# remove leading 'on'
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "yellow"

[git_status]
style = "yellow"

[golang]
disabled = true

[line_break]
disabled = false

[nodejs]
disabled = true

[package]
disabled = true

[python]
disabled = true

[time]
disabled = false
format = '[$time]($style) '
style = 'bold cyan'
