"$schema" = 'https://starship.rs/config-schema.json'

# print the timestamp on the right hand side
right_format = """$cmd_duration$time"""

[cmd_duration]
format = '⏱️[$duration]($style) '

[directory]
repo_root_style = "bold yellow"
# show initials
# fish_style_pwd_dir_length = 3

[git_branch]
# remove leading 'on'
format = '[$symbol$branch(:$remote_branch)]($style) '

[line_break]
disabled = false

[time]
disabled = false
format = '[$time]($style) '
