"$schema" = 'https://starship.rs/config-schema.json'

# print the timestamp on the right hand side
right_format = """$cmd_duration$time"""

[cmd_duration]
format = '[$duration]($style)-'

[directory]
truncation_symbol = "/../"

[git_branch]
# remove leading 'on'
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "yellow"

[git_status]
style = "yellow"

[line_break]
disabled = false

[time]
disabled = false
format = '[$time]($style) '
style = 'bold cyan'
